const GodMode = require('./godMode');
const AIProvider = require('./aiProvider');

/**
 * Smart God Mode Agent
 * Uses AI (Gemini/OpenRouter) to plan and execute complex multi-step system tasks.
 */
class SmartGodModeAgent {
    constructor(aiProvider, sendMessageCallback) {
        this.godMode = new GodMode();
        this.aiProvider = aiProvider || new AIProvider();
        this.sendMessageCallback = sendMessageCallback; // Function to send messages/files back to user
        console.log('[SmartGodMode] 🧠 Initialized with AI capabilities');
    }

    /**
     * Main entry point: Interpret and Execute
     */
    async processRequest(userMessage) {
        console.log(`[SmartGodMode] 🧠 Analyzing request: "${userMessage}"`);

        try {
            // 1. Generate Execution Plan using AI
            const plan = await this.aiProvider.generatePlan(userMessage);

            if (!plan) {
                return "⚠️ I couldn't understand how to do that using my system tools.";
            }

            if (plan.error) {
                return `⚠️ Planning Error: ${plan.error}`;
            }

            // 2. Execute the Plan
            return await this.executePlan(plan);

        } catch (error) {
            console.error('[SmartGodMode] Critical Error:', error);
            return `❌ Critical Error: ${error.message}`;
        }
    }

    /**
     * Execute the JSON plan generated by AI
     */
    async executePlan(plan) {
        console.log('[SmartGodMode] 📝 Executing Plan:', JSON.stringify(plan, null, 2));

        const results = [];

        // Give user immediate feedback plan is starting
        if (plan.thought) {
            console.log(`[SmartGodMode] 💭 Musing: ${plan.thought}`);
            results.push(`💭 **Thought:** ${plan.thought}`);
        }

        for (const step of plan.steps) {
            try {
                console.log(`[SmartGodMode] ▶️ Step: ${step.tool} - ${step.description}`);

                let result = "";

                switch (step.tool) {
                    case 'file_write':
                        result = await this.godMode.writeFile(step.params.path, step.params.content);
                        break;

                    case 'file_read':
                        result = await this.godMode.readFile(step.params.path);
                        break;

                    case 'file_list':
                        result = await this.godMode.listFiles(step.params.path || '.');
                        break;

                    case 'file_delete':
                        result = await this.godMode.deleteFile(step.params.path);
                        break;

                    case 'folder_create':
                        result = await this.godMode.createFolder(step.params.path);
                        break;

                    case 'folder_delete':
                        result = await this.godMode.deleteFolder(step.params.path);
                        break;

                    case 'browser_open':
                        // Check for profiles if not specified
                        let profile = step.params.profile;
                        const browserType = step.params.browser || 'chrome'; // 'chrome', 'brave', 'edge'

                        if (!profile) {
                            const profiles = await this.godMode.getChromeProfiles(); // Works for Chrome-based browsers? Need to check paths for Brave later.
                            // For now, only attempt profile detection if browser is Chrome (default) or we implement getBraveProfiles
                            if (browserType === 'chrome' && profiles.length > 0) {
                                // AUTO-SELECT Logic
                                if (profiles.includes('Default')) {
                                    profile = 'Default';
                                } else {
                                    profile = profiles[0];
                                }
                                console.log(`[SmartGodMode] 🤖 Auto-selected Chrome Profile: ${profile}`);
                            }
                        }

                        // Ensure we have a URL to navigate to, otherwise Puppeteer opens about:blank
                        const targetUrl = step.params.url || 'https://www.google.com';
                        result = await this.godMode.browserAutomate(targetUrl, [], browserType, profile);
                        break;

                    case 'browser_navigate':
                        result = await this.godMode.browserNavigate(step.params.url);
                        break;

                    case 'browser_search':
                        result = await this.godMode.webSearch(step.params.query);
                        break;

                    case 'youtube_play':
                        result = await this.godMode.youtubePlay(step.params.query);
                        break;

                    case 'app_open':
                        // Use known apps mapping if possible, else try raw start
                        const appName = step.params.name.toLowerCase();
                        if (appName.includes('notepad')) result = await this.godMode.executeCommand('start notepad');
                        else if (appName.includes('calc')) result = await this.godMode.executeCommand('start calc');
                        else if (appName.includes('paint')) result = await this.godMode.executeCommand('start mspaint');
                        else if (appName.includes('explorer')) result = await this.godMode.executeCommand('start explorer');
                        else if (appName.includes('cmd')) result = await this.godMode.executeCommand('start cmd');
                        else result = await this.godMode.openApp(step.params.name);
                        break;

                    case 'app_close':
                        result = await this.godMode.closeApp(step.params.name);
                        break;

                    // [NEW] Shortcut: Click element by text/selector
                    case 'browser_click':
                        const selector = step.params.selector || `text=${step.params.text}`;
                        // We need a more robust way to click. 
                        // For now, re-using browserAutomate or adding specific click method to GodMode.
                        // Ideally GodMode should exposes `click(selector)` directly.
                        // Let's use `godMode.browserAutomate` for now as it handles selectors well.
                        result = await this.godMode.browserAutomate(null, [{ type: 'click', selector: selector }]);
                        break;

                    case 'file_download':
                        result = await this.godMode.downloadFile(step.params.url, step.params.path);
                        break;

                    case 'browser_content':
                        result = await this.godMode.getPageContent();
                        break;

                    case 'run_script':
                        console.log(`[SmartGodMode] 📜 Executing Dynamic Script (${step.params.language})`);
                        if (step.params.language === 'node' || step.params.language === 'javascript') {
                            result = await this.godMode.executeScript(step.params.code);
                        } else {
                            result = "⚠️ Only Node.js/JavaScript scripts are supported for now.";
                        }
                        break;

                    case 'whatsapp_send': // Send file/message back to user
                        if (this.sendMessageCallback) {
                            console.log(`[SmartGodMode] 📤 Sending WhatsApp: ${step.params.path || step.params.content}`);
                            // If path is provided, it's likely a file send (which needs implementation in Client or here to wrap in MessageMedia)
                            // For now assuming 'sendMessageCallback' handles simple text or we can enhance it.
                            // Actually, let's treat it as a text message or a file path to send.
                            // We need to assume the callback handles { text, mediaPath } or just text.
                            await this.sendMessageCallback(step.params.path, step.params.caption || "");
                            result = "Message/File sent to user";
                        } else {
                            result = "⚠️ WhatsApp callback not configured.";
                        }
                        break;

                    case 'screen_shot':
                        result = await this.godMode.executeCommand('snippingtool /clip');
                        break;

                    case 'system_exec':
                    case 'shell_exec': // Alias
                        result = await this.godMode.executeCommand(step.params.command);
                        break;

                    default:
                        result = `⚠️ Unknown tool: ${step.tool}`;
                }

                results.push(`✅ **${step.description}**\n${result}`);

            } catch (stepError) {
                console.error(`[SmartGodMode] ❌ Step Failed: ${step.description}`, stepError);
                results.push(`❌ **Failed:** ${step.description}\nError: ${stepError.message}`);
                // Continue execution? Maybe stop for critical errors?
                // For now, let's keep going as some steps might be independent.
            }
        }

        // Return simple confirmation instead of verbose report
        return "✅ Done boss."; // Executed successfully
    }
}

module.exports = SmartGodModeAgent;
